cwb:
  token: CWB_TOKEN
  query:
    format: json
    elements: PoP12h,AT,WeatherDescription,PoP6h

line:
  bot:
    channelToken: LINE_CHANNEL_SERCRET
    channelSecret: LINE_CHANNEL_TOKEN
  ids:
    - LINE_USER_ID
-